### PR TITLE
Review(features)

### PR DESCRIPTION
**Pull request by ianchobuilds**

### CODE REVIEW

**Comment by ianchobuilds** [comment]
@googlebot  I signed it!

**Comment by ianchobuilds** [comment]
@googlebot Then please don't mind this pull request and can you contribute my other pull request https://github.com/angular/angular-ko/pull/4 ? And please let me know how I can exclude my pull request from your detecting when I push angular.io update?

**Comment by ianchobuilds** [comment]
@googlebot Could you please check my comments above and in #4. 😭 😢 
I assure you that #9 is also authored by me.

**Comment by ianchobuilds** [comment]
@googlebot Those commits are all already  authorized in angular.io repo. You're mistaken, please approve my other commits..

**Comment by naomiblack** [comment]
@googlebot these commits are ok

**Comment by naomiblack** [comment]
@googlebot these commits are ok

**Pull request merged**
